module.exports = {
  restrictedChannels: {
    // main-chat
    "1493177804337053716": [
      "mci",
      "mc",
      "cd",
      "effect",
      "lb",
      "starter",
      "pullinfo",
      "team",
      "convert",
      "ryuma",
      "finv",
      "ci",
      "help",
      "balance",
      "pirate",
      "inv",
      "vote",
      "patreon",
      "op",
      "market",
      "trade",
      "profile",
      "awaken",
      "wp",
      "unequip",
      "showskins",
      "setskin",
      "summon",
      "add",
      "remove",
      "fshop",
      "fbuy",
      "fbreak",
      "travel",
      "sail",
      "ship",
      "shipupgrade",
      "wupgrade",
      "equipfruit",
      "all",
      "marines",
      "level",
      "open",
      "daily",
      "treasure",
      "imu",
      "redeemcode",
      "quest",
    ],

    "1502525406161666058": [
      "mm",
      "marines",
    ],

    // trade-discuss
    "1497584870812291294": [
      "trade",
      "convert",
      "rum",
      "mci",
      "mc",
      "finv",
      "ci",
      "effect",
      "sac",
      "balance",
      "inv",
      "fshop",
      "fbuy",
      "fbreak",
      "marines",
      "patreon",
      "market",
      "op",
      "profile",
      "awaken",
      "effect",
      "showskins",
      "setskin",
      "cd",
      "wp",
      "wupgrade",
      "equipfruit",
      "all",
      "level",
      "imu",
    ],

    "1502220117331804250": [
      "trade",
      "convert",
      "rum",
      "mci",
      "marines",
      "mc",
      "finv",
      "fshop",
      "fbuy",
      "fbreak",
      "ci",
      "op",
      "balance",
      "inv",
      "effect",
      "showskins",
      "setskin",      
      "patreon",
      "market",
      "profile",
      "awaken",
      "effect",
      "cd",
      "wp",
      "wupgrade",
      "equipfruit",
      "all",
      "level",
      "imu",
    ],

    // raid
    "1500131562430398604": [
      "mci",
      "mc",
      "raid",
      "marines",
      "raidteam",
      "raidteamadd",
      "raidmissing",
      "raidteamdelete",
      "raidteamremove",
      "wupgrade",
      "open",
      "summon",
      "wp",
      "add",
      "op",
      "remove",
      "bal",
      "swap",
      "team",
      "killraid",
      "showskins",
      "setskin",
      "inv",
      "finv",
      "ci",
      "awaken",
    ],

    "1500131596135698443": [
      "mci",
      "mc",
      "raid",
      "raidteam",
      "marines",
      "raidteamadd",
      "raidmissing",
      "raidteamdelete",
      "raidteamremove",
      "wupgrade",
      "open",
      "summon",
      "wp",      
      "add",
      "op",
      "remove",
      "bal",
      "swap",
      "team",
      "killraid",
      "showskins",
      "setskin",
      "inv",
      "finv",
      "ci",
      "awaken",
    ],

    "1500131618474430615": [
      "mci",
      "mc",
      "raid",
      "raidteam",
      "raidteamadd",
      "raidmissing",
      "raidteamdelete",
      "raidteamremove",
      "wupgrade",
      "open",
      "summon",
      "wp",      
      "add",
      "op",
      "remove",
      "bal",
      "marines",
      "swap",
      "team",
      "killraid",
      "showskins",
      "setskin",
      "inv",
      "finv",
      "ci",
      "awaken",
    ],

    "1500131637793394819": [
      "mci",
      "mc",
      "raid",
      "raidteam",
      "raidteamadd",
      "raidmissing",
      "raidteamdelete",
      "marines",
      "raidteamremove",
      "wupgrade",
      "summon",
      "open",
      "wp",      
      "add",
      "op",
      "remove",
      "bal",
      "swap",
      "team",
      "killraid",
      "showskins",
      "setskin",
      "inv",
      "finv",
      "ci",
      "awaken",
    ],

    "1500131660161880114": [
      "mci",
      "mc",
      "raid",
      "marines",
      "raidteam",
      "raidteamadd",
      "raidmissing",
      "raidteamdelete",
      "raidteamremove",
      "wupgrade",
      "open",
      "summon",
      "wp",
      "add",
      "op",
      "remove",
      "bal",
      "swap",
      "team",
      "killraid",
      "showskins",
      "setskin",
      "inv",
      "finv",
      "ci",
      "marines",
      "awaken",
    ],

    // news-coo
    "1497586206110912733": [],

    // suggestions
    "1497542212148396223": [],
  },

  blockedCommands: {
    // islands
    "1502519130455277568": ["raid"],
    "1497574788401725562": ["raid"],
    "1497574814762663936": ["raid"],
    "1497574860942086335": ["raid"],
    "1500131876101423154": ["raid"],
    "1503018874289782834": ["raid"],
    "1503018907936489492": ["raid"],
    "1503018937250615478": ["raid"],
    "1504795525935796315": ["raid"],
    "1504795551550410872": ["raid"],
    "1508308751348662332": ["raid"],

    // mother flame
    "1502557193415823401": ["raid"],

    // vivre card
    "1504462180135997492": ["raid"],

    //pangea castle
    "1504743963729330296": ["raid"],
  },

  alwaysAllowedCommands: [],
};