module.exports = {
  restrictedChannels: {
    // main-chat
    "1493177804337053716": [
      "mci",
      "finv",
      "ci",
      "balance",
      "inventory",
      "patreon",
      "market",
      "profile",
      "awaken",
      "wp",
      "wupgrade",
      "equipfruit",
      "all",
      "level",
      "open",
      "daily",
      "treasure",
      "imu",
    ],

    // trade-discuss
    "1497584870812291294": [
      "trade",
      "mci",
      "finv",
      "ci",
      "balance",
      "inventory",
      "patreon",
      "market",
      "profile",
      "awaken",
      "wp",
      "wupgrade",
      "equipfruit",
      "all",
      "level",
      "imu",
    ],

    // raid
    "1500131562430398604": [
      "mci",
      "raid",
      "raidteam",
      "raidteamadd",
      "raidmissing",
      "raidteamdelete",
      "raidteamremove",
      "add",
      "remove",
      "swap",
      "team",
      "killraid",
      "inventory",
      "finv",
      "ci",
      "awaken",
    ],

    "1500131596135698443": [
      "mci",
      "raid",
      "raidteam",
      "raidteamadd",
      "raidmissing",
      "raidteamdelete",
      "raidteamremove",
      "add",
      "remove",
      "swap",
      "team",
      "killraid",
      "inventory",
      "finv",
      "ci",
      "awaken",
    ],

    "1500131618474430615": [
      "mci",
      "raid",
      "raidteam",
      "raidteamadd",
      "raidmissing",
      "raidteamdelete",
      "raidteamremove",
      "add",
      "remove",
      "swap",
      "team",
      "killraid",
      "inventory",
      "finv",
      "ci",
      "awaken",
    ],

    "1500131637793394819": [
      "mci",
      "raid",
      "raidteam",
      "raidteamadd",
      "raidmissing",
      "raidteamdelete",
      "raidteamremove",
      "add",
      "remove",
      "swap",
      "team",
      "killraid",
      "inventory",
      "finv",
      "ci",
      "awaken",
    ],

    "1500131660161880114": [
      "mci",
      "raid",
      "raidteam",
      "raidteamadd",
      "raidmissing",
      "raidteamdelete",
      "raidteamremove",
      "add",
      "remove",
      "swap",
      "team",
      "killraid",
      "inventory",
      "finv",
      "ci",
      "awaken",
    ],

    // news-coo
    "1497586206110912733": [],

    // suggestions
    "1497542212148396223": [],
  },

  blockedCommands: {
    // islands
    "1497574337421639680": ["raid"],
    "1497574788401725562": ["raid"],
    "1497574814762663936": ["raid"],
    "1497574860942086335": ["raid"],
  },

  alwaysAllowedCommands: [],
};